# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 507)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_open_cam = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_cam.setGeometry(QtCore.QRect(20, 20, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_cam.setFont(font)
        self.btn_open_cam.setObjectName("btn_open_cam")
        self.label_show_camera = QtWidgets.QLabel(self.centralwidget)
        self.label_show_camera.setEnabled(True)
        self.label_show_camera.setGeometry(QtCore.QRect(220, 30, 600, 400))
        self.label_show_camera.setObjectName("label_show_camera")
        self.name_input = QtWidgets.QTextEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(20, 220, 141, 41))
        self.name_input.setObjectName("name_input")
        self.btn_detection_face = QtWidgets.QPushButton(self.centralwidget)
        self.btn_detection_face.setGeometry(QtCore.QRect(20, 60, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_detection_face.setFont(font)
        self.btn_detection_face.setObjectName("btn_detection_face")
        self.btn_save_face = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_face.setGeometry(QtCore.QRect(20, 100, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save_face.setFont(font)
        self.btn_save_face.setObjectName("btn_save_face")
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(20, 140, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.quit.setFont(font)
        self.quit.setObjectName("quit")
        self.label_save_face = QtWidgets.QLabel(self.centralwidget)
        self.label_save_face.setGeometry(QtCore.QRect(30, 290, 150, 150))
        self.label_save_face.setObjectName("label_save_face")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(30, 190, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_open_cam.setText(_translate("MainWindow", "打开摄像头"))
        self.label_show_camera.setText(_translate("MainWindow", "camera_frame"))
        self.btn_detection_face.setText(_translate("MainWindow", "人脸检测"))
        self.btn_save_face.setText(_translate("MainWindow", "人脸保存"))
        self.quit.setText(_translate("MainWindow", "退出"))
        self.label_save_face.setText(_translate("MainWindow", "TextLabel"))
        self.label_name.setText(_translate("MainWindow", "输入名称:"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MainWindow()
    ex.show()
    sys.exit(app.exec_())